git:
    submodules: true
services:
    - mysql
    - mongodb
language: cpp
before_install:
    - ./.build/travis/presetup ${TRAVIS_OS_NAME}
install:
    - ./.build/travis/setup ${TRAVIS_OS_NAME}
    - sudo apt-get install -qq libssl-dev -y
script:
    - # Snappy
    - sudo apt-get install libsnappy-dev
    - # ThorsSerializer
    - git clone https://github.com/Loki-Astari/ThorsSerializer.git
    - cd ThorsSerializer
    - ./configure --disable-vera --with-boost=/tmp/extra
    - make
    - sudo make install
    - cd ..
    - # Setting up DB
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$(pwd)/build/lib
    - cat ./src/MySQL/test/data/init.travis.sql | mysql -B -h  127.0.0.1 -u root
    - cat ./src/MySQL/test/data/data.sql        | mysql -B -h  127.0.0.1 -u test -ptestPassword test
    - cat ./src/Mongo/test/data/init.mongo      | mongo --host 127.0.0.1
    - cat ./src/Mongo/test/data/data.mongo      | mongo --host 127.0.0.1
    - # Build
    - ./configure --with-boost=/tmp/extra --disable-travis
    - cat config.log
    - export PATH=${PATH}:$(pwd)/build/bin
    - make
after_success:
    - ./CreateHeaderOnly  master
    - bash <(curl -s https://codecov.io/bash)
branches:
    only:
        - master
        - "/^Feature-.*$/"
env:
    global:
    - secure: D5HPaNoM+cbZLcfqGvudY3irPd27q89npzr7jlaVjs1m782bii8XCKWwrwNQfge/7mtaY7RRDxdFJkRssVno5HaLItOg/MT6gBinyQGenPZXeh7ia2CYkeuiRhKrEfKAMhCcoe5RafYbCDWq8w5eZ6iMnRoFUiA66cWGlF1vBI4=
