git:
    submodules: true
language: cpp
before_install:
    - ./.build/travis/presetup ${TRAVIS_OS_NAME}
install:
    - ./.build/travis/setup ${TRAVIS_OS_NAME}
    - sudo apt-get install -qq libssl-dev
    - sudo apt-get install mysql-server
    - sudo systemctl start mysql
    - echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'testPassword';FLUSH PRIVILEGES;" | mysql -u root
    - cat src/MySQL/test/data/init.travis.sql | mysql --force --user=root --password=testPassword
    - cat src/MySQL/test/data/data.sql | mysql --force --user=root --password=testPassword
    - sudo apt install postgresql postgresql-contrib
    - sudo systemctl start postgresql
    - cat src/Postgres/test/data/init.sql | sudo -u postgres psql 
    - echo "ALTER USER postgres WITH PASSWORD 'testPassword';" | sudo -u postgres psql postgres
script:
    - ./configure --with-boost=/tmp/extra
    - make
after_success:
    - bash <(curl -s https://codecov.io/bash)
branches:
    only:
        - master
        - "/^Feature-.*$/"
env:
    global:
    - secure: D5HPaNoM+cbZLcfqGvudY3irPd27q89npzr7jlaVjs1m782bii8XCKWwrwNQfge/7mtaY7RRDxdFJkRssVno5HaLItOg/MT6gBinyQGenPZXeh7ia2CYkeuiRhKrEfKAMhCcoe5RafYbCDWq8w5eZ6iMnRoFUiA66cWGlF1vBI4=
