git:
    submodules: false
language: cpp
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
install:
    - sudo apt-get install -qq g++-7
    - sudo apt-get install python-dev -y
    - sudo apt-get install -qq libssl-dev
    - sudo apt-get install -qq libboost-all-dev
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
    - wget -O boost_1_56.tar.gz http://sourceforge.net/projects/boost/files/boost/1.56.0/boost_1_56_0.tar.gz/download
    - tar xzf boost_1_56.tar.gz;cd boost_1_56_0/;mkdir -p /tmp/extra;./bootstrap.sh --prefix=/tmp/extra
    - ./b2 cxxflags="-Wno-strict-aliasing -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-placement-new" --with-system --with-context --with-coroutine
    - sudo ./b2 --with-system --with-context --with-coroutine install | awk 'NR == 1 || NR % 25 == 0'
    - cd ..
    - sudo apt-get install mysql-server
    - sudo systemctl start mysql; sleep 10
    - echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'testPassword';FLUSH PRIVILEGES;" | mysql -u root
    - cat src/MySQL/test/data/init.travis.sql | mysql --force --user=root --password=testPassword
    - cat src/MySQL/test/data/data.sql | mysql --force --user=root --password=testPassword
    - sudo apt install postgresql postgresql-contrib
    - cat src/Postgres/test/data/init.sql | sudo -u postgres psql 
    - echo "ALTER USER postgres WITH PASSWORD 'testPassword';" | sudo -u postgres psql postgres
script:
    - ./configure --with-boost=/tmp/extra
    - make
after_success:
    - bash <(curl -s https://codecov.io/bash)
