#!/bin/bash

find src -type f -not -path '*/test/*' '(' -name '*.cpp' -or -name '*.tpp' ')' | awk -F/ '{print $NF}' > upload

for file in $(find src -type f -name '*.gcov'); do
    echo "<<<<<< EOF" >> upload
    cat "$file" | sed -e 's/\(0:[A-Za-z]*\):[A-Za-z.]*\//\1:/' >> upload
done

