#!/bin/bash

function mysqlTry {
    working=1

    while [[ "${working}" == "1" ]]; do
        echo $4 | mysql --user=$1 --password=$2 $3 2> /dev/null > /tmp/out
        if ( test $(cat /tmp/out | wc -l) -ge $5); then
            working=0
        fi
    done
    cat /tmp/out
}

c1=$(mysqlTry test testPassword test 'SELECT COUNT(ID) FROM PeopleExtra WHERE ID=15'  1 | tail -1)
mysqlTry test testPassword test 'DELETE FROM PeopleExtra' 0

if [[ "$c1" != "1" ]]; then
    echo "insertTestTearDown Failed:"
    echo "Expected: c1 => 1  Got (${c1})"
    exit 1
fi

