#!/bin/bash

function mysqlTry {
    working=1

    while [[ "${working}" == "1" ]]; do
        echo $4 | mysql --user=$1 --password=$2 $3 2> /dev/null > /tmp/out
        if ( test $(cat /tmp/out | wc -l) -ge $5); then
            working=0
        fi
    done
    cat /tmp/out
}

mysqlTry test testPassword test 'INSERT INTO PeopleExtra(ID, Name, Age, Sex, Height) VALUES(21, "Tom Hanks", 91, "F", 332.56)' 0
c1=$(mysqlTry test testPassword test 'SELECT COUNT(ID) FROM PeopleExtra WHERE ID=21'  1 | tail -1)

if [[ "$c1" != "1" ]]; then
    echo "updateTestSetUp Failed:"
    echo "Expected: c1 => 1  Got (${c1})"
    exit 1
fi

