
THORSANVIL_ROOT				?= $(realpath ../../)

TARGET						= ThorsDBTest.test
LDLIBS_EXTERN_BUILD			= $(ThorSerialize_ROOT_LIB)
NO_HEADER					= 1

UNITTEST_LINK_LIBS			= ThorsDB ThorsSocket

include $(THORSANVIL_ROOT)/build/tools/Makefile

