
THORSANVIL_ROOT				?= $(realpath ../../)

TARGET						= ThorsDBTest.test
UNITTEST_LINK_LIBS			= ThorsDB ThorsLogging
UNITTEST_RUNTIME_PATH		= $(ThorsSerialize_ROOT_DIR)/lib
NO_HEADER					= 1

include $(THORSANVIL_ROOT)/build/tools/Makefile

