
THORSANVIL_ROOT				?= $(realpath ../../)

TARGET						= ThorsDB.defer
NAMESPACE					= ThorsAnvil::DB::Access

LDLIBS_EXTERN_BUILD			= $(ThorSerialize_ROOT_LIB)
UNITTEST_LDLIBS				= -ldl


include $(THORSANVIL_ROOT)/build/tools/Makefile

