
THORSANVIL_ROOT				?= $(realpath ../../)

TARGET						= ThorSQL.lib
LDLIBS						= -lssl -lcrypto
CXXFLAGS					= $(crypto_ROOT_INCDIR)
LDFLAGS						= $(crypto_ROOT_LIBDIR)

include $(THORSANVIL_ROOT)/build/tools/Makefile




