
THORSANVIL_ROOT				?= $(realpath ../../)
COVERAGE_REQUIRED			= 60

TARGET						= ThorsDBCommon.defer
DEFER_NAME					= ThorsDB
CXXFLAGS					= $(crypto_ROOT_INCDIR)
UNITTEST_LDLIBS				= $(crypto_ROOT_LIBDIR) -lssl -lcrypto
NO_HEADER					= 1

include $(THORSANVIL_ROOT)/build/tools/Makefile

