
THORSANVIL_ROOT				= $(realpath ../)

TARGET						= ThorsIOUtil ThorsCrypto ThorsDB ThorsDBCommon MySQL Postgres Mongo ThorsDBBuild ThorsDBBuildTest

include $(THORSANVIL_ROOT)/build/tools/Project.Makefile




