
THORSANVIL_ROOT				= $(realpath ../)

TARGET						= ThorsCrypto ThorsSocket ThorsDB ThorsDBCommon MySQL Postgres Mongo ThorsDBBuild ThorsDBBuildTest

include $(THORSANVIL_ROOT)/build/tools/Project.Makefile




